### ISSUE TITLE
How to insert line break?

### ISSUE THREAD

**Issue by bukanvalen** [aahnik/wappdriver#37]
### I use it like this
```python
with WhatsApp() as bot:
    for person in recipients:
        bot.send(person, f'Hello {person}\nNew line test')
```

But then the messages were split into 2 separate messages. I know that the Enter key is the send key in WhatsApp Web. That's why I ask here, how to insert a line break? Thank you

**Comment by aahnik** [comment]
Thank you for raising this issue.

Earlier this used to work. But today I checked, it is working no more. I don't know why.

In WhatsApp Web <kbd>SHIFT </kbd> + <kbd>ENTER</kbd> goes to new line. I know this and had implemented in my code.

See [this](https://github.com/aahnik/wappdriver/blob/b44865a6ff0f22483e78f489907a531f2b2f3a70/wappdriver/driver.py#L78).

It is working while done manually, but inside the script, it seems not to work.

**Comment by aahnik** [comment]
Actually, I had made a small mistake. I am solving this now.

**Comment by aahnik** [comment]
I fixed this issue just now.

##  Please update the package in your computer.

```shell
pip install --upgrade wappdriver
```

### Now your same code would do the work. 😇

You don't have to do anything to your code. 😊☺️🙂🙃. Just update the package, and everything will work fine.

Thanks a lot for reporting this. There was a small mistake in my code, which is now fixed.

**Comment by aahnik** [comment]
Please update the package, test it once and say me if it is working as expected.

**Comment by bukanvalen** [comment]
Thank you so much! Now it works perfectly. Do you mind telling me what did you change and how it fixes the issue? I'm still learning Python, so if you could explain it, I would really appreciate it. Thanks in advance!

**Comment by aahnik** [comment]
you can understand simply by seeing my commit e9b44d921f9444fd1422fad51179433daf0c6ed6

i just removed a tab :smile: 
it was a silly mistake from my part

**Comment by bukanvalen** [comment]
One more thing, thank you so much for creating this. I was having trouble understanding Selenium and then I found your article on DEV. I was really in a pinch to message a bunch of people with custom messages that are tailored based on their name and gender. Now I can just open up Python and run your script, rather than messaging them one by one with some little editing in between.

**Comment by aahnik** [comment]
This is offtopic, for chatting with me, please use Telegram [@aahnikdaw](https://telegram.me/aahnikdaw)

**Comment by aahnik** [comment]
That was the main purpose of creating this package. To let people not worry about selenium, chrome driver, selectors, etc, and allow people to easily send messages.

In the future, I will build a command-line version, where you can easily send messages, without even writing any python code.

If you are interested in Python and automation, you may see my Telegram Channel, where I post interesting stuff.

 [![telegram-channel](https://img.shields.io/badge/channel-@aahnikd-yellowgreen?logo=telegram)](https://telegram.me/aahnikd)

**Comment by bukanvalen** [comment]
I'll be waiting for it, thanks for the information!
