### ISSUE TITLE
Page Loads but no inputs

### ISSUE THREAD

**Issue by ramzcode** [aahnik/wappdriver#49]
After running the following, the chrome loads with my WhatsApp account signed in but nothing happens after that.
python3.8 ./script.py

After a timeout it exists with an usual error.

**Comment by aahnik** [comment]
Please show the error. Copy and paste the output.

**Comment by ramzcode** [comment]
![wappdriver](https://user-images.githubusercontent.com/76745955/109138840-d0f26d80-7780-11eb-890d-a382b290c321.png)

**Comment by ramzcode** [comment]
This is a amazing work. Yesterday all worked find after lots or fixes. Now again facing one of the issue.

**Comment by mrwenjie** [comment]
I have encountered the same issue as well. Hope you take a look at it. Thank you again aahnik.

**Comment by aahnik** [comment]
@ramzcode  and @mrwenjie, I will look into the issue.

But please understand
- WhatsApp has a paid Business API, and it may block third-party scripts in future
- I am personally against WhatsApp's privacy policy and will be leaving WhatsApp after August
- Telegram provides an official and free API, that works smoothly, as it talks to Telegram's servers directly
- Wappdriver just clicks and types in a chrome browser


Thus I strongly recommend users to switch to Telegram, and bring their friends and family with them.

If you use WhatsApp for business and need a reliable system, please read this https://www.whatsapp.com/business/api/

**Comment by aahnik** [comment]
As I personally don't use WhatsApp much, I really don't have much motivation to continue working on this repository.

I recommend taking a look at some Telegram bots and scripts made by me :

- https://github.com/aahnik/run-py-bot

- https://github.com/aahnik/telegram-chat-forward

- https://github.com/aahnik/howdoi-telegram

**Comment by aahnik** [comment]
Check out the Telegram related APIs

- Telethon    https://github.com/LonamiWebs/Telethon
- python-telegram-bot    https://github.com/python-telegram-bot/python-telegram-bot

both of them have a large number of users and provide fantastic help and support.

You can do a lot with these APIs
